### PR TITLE
fix sets parse

### PR DESCRIPTION
**Pull request by angrz**

### CODE REVIEW

**Comment by elgris** [comment]
Can you provide more information please? Which version of Aerospike introduces a change which replaces `set_name=` with `set=` in output of RequestInfo?

I just checked this doc: http://www.aerospike.com/docs/reference/info, looks like it still uses `set_name=` in output

**Comment by angrz** [comment]
but aerospike build 3.9.1.1 returns info with following format:
ns=order:set=suppliers:objects=0:memory_data_bytes=0:deleting=false:stop-writes-count=0:set-enable-xdr=use-default:disable-eviction=false

**Comment by angrz** [comment]
ok, we could keep both formats, what about this one?

```		
if len(opt) > 4 && opt[:4] == "set=" {
	sets = append(sets, opt[4:])
}
if len(opt) > 9 && opt[:9] == "set_name=" {
	sets = append(sets, opt[9:])
}
```

**Comment by elgris** [comment]
This hack needs some documentation :).

Could you please add 2 comments there? 1st block works for aerospike from v.3.9.0 and above, 2nd block - for legacy versions (below 3.9.0). Also I would go for `if ... else if ...` instead of 2 `if`s

**Comment by angrz** [comment]
done

**Comment by elgris** [comment]
thanks!

**Pull request merged**
